src/Contracts/CreateSimplifiedStatementEventInterface.php
src/Contracts/StatementCreatorInterface.php

**Ticket:** https://yaits.demos-deutschland.de/T30254
Description:
Add new contracts
- CreateSimplifiedStatementEventInterface.php
- StatementCreatorInterface.php
related PRs:
- Core : https://github.com/demos-europe/demosplan-core/pull/402
- Demosplan addon : https://github.com/demos-europe/demosplan-addon/pull/2
Delete the checkbox if it doesn't apply/isn't necessary.

Fix (ref: T30254): add contracts

---

src/Contracts/Entities/UuidEntityInterface.php

**Ticket:** https://yaits.demos-deutschland.de/T30254
Description: add inheritance
Delete the checkbox if it doesn't apply/isn't necessary.

Fix (ref: T30254): adjust UuidEntityInterface

---

src/Contracts/ResourceType/AddonResourceType.php
src/Contracts/ResourceType/FileResourceTypeInterface.php
src/Contracts/ResourceType/ProcedureResourceTypeInterface.php
src/Contracts/ResourceType/ResourceTypeServiceInterface.php
src/Contracts/ResourceType/StatementResourceTypeInterface.php
src/Controller/APIController.php
src/Permission/Conditions/PropertyIsCurrentProcedureId.php
src/Permission/Conditions/PropertyIsCurrentUserId.php
src/Permission/Conditions/UserIsInCurrentCustomer.php

Ticket:https://yaits.demos-deutschland.de/T30254
Description: more adjustements 
- remove is available method usage
- adjust exception

Fix (ref: T30254): adjust ApiController

---

src/Contracts/ResourceType/ResourceTypeServiceInterface.php

Ticket: T30254
Description: remove inheritance

Feat (ref: T30254): adjust ResourceTypeServiceInterface

---

src/Contracts/ResourceType/AddonResourceType.php

Ticket : T30254
Description : adjust AddonResourceType

Feat (ref: T30254): adjust AddonResourceType

---

src/Contracts/ResourceType/AddonResourceType.php

Ticket: T30254
Description: more needed adjustements

Feat (ref: T30254): readjust AddonResourceType

---

src/Contracts/ResourceType/AddonResourceType.php

Ticket: T30254
Description: more needed adjustements

Feat (ref: T30254): add missing parameter in construct

---

src/Contracts/PermissionsInterface.php

Ticket: T31336
Description: more fixes

F(ref: T31336): adjust return type

---

src/Contracts/Events/AddonMaintenanceEventInterface.php

Description: add AddonMaintenanceEventInterface

F(ref: T29871): add AddonMaintenanceEventInterface

---

src/Contracts/Factory/PercentageDistributionFactoryInterface.php
src/Contracts/ValueObject/PercentageDistributionInterface.php

Ticket: https://yaits.demos-deutschland.de/T29871
Description: This PR adds the PercentageDistributionInterface to make the PercentageDistribution value object accessable for addons.

feat (T29871): add PercentageDistributionInterface.php

---

src/Contracts/Events/HandleEmailAddressesEventInterface.php
src/Contracts/ResourceType/OriginalStatementResourceTypeInterface.php

Description: 
add new event interface ( contract )
adjust OriginalStatementResourceTypeInterface : add missing Templates parameters

F add event contract

---

src/Contracts/ResourceType/AddonResourceType.php

Ticket:
https://yaits.demos-deutschland.de/T31926
Description:
To prevent trying to create a new instance of an interface when using the propertyAutoPathTrait
- the createChild method is overwritten and adjusted to always call the findImplementationOfInterface method.

feature (refs T31926) Overwrite CreateChild Method of PropertyAutoPathTrait inside AddonResourceType

---

src/Logic/Rpc/RpcMethodAddonSolverInterface.php

Ticket: T31511
Description: add RpcMethodAddonSolverInterface

F T31511 add RpcMethodAddonSolverInterface

---

src/Contracts/ValueObject/ValueObjectInterface.php

Description: adjust ValueObjectInterface
- add lock method

F adjust ValueObjectInterface

---

composer.json
src/Contracts/Entities/EntityChangeInterface.php
src/Logic/ResourceChange.php

Continuation of https://github.com/demos-europe/demosplan-core/pull/1295
https://github.com/demos-europe/demosplan-core/pull/1322 must be merged first

chore: remove obsolete ES indexing and update PHP to 8.1

---

src/Contracts/Repositories/MapRepositoryInterface.php

Descripton: remove wrong use statement

F remove wrong use statement

---

src/Contracts/Config/GlobalConfigInterface.php
src/Contracts/Events/GetDatasheetVersionEventInterface.php

Ticket: T32243
Description: needed adjustement related to the removal of procedure bundle

F T32243 adjustement related to the removal of procedure bundle

---

src/Contracts/Entities/UserInterface.php

Ticket:
https://yaits.demos-deutschland.de/T32212
Description:
fix return type in addonuserInterface : methode: setSalt()

feature (refs T32212): fix return userInterface

---

CHANGELOG.md

prepare changelog for version 0.1

chore: prepare changelog version 0.1

---

CHANGELOG.md

chore: prepare changelog version 0.1.1

---

src/Contracts/Config/GlobalConfigInterface.php
src/Contracts/Events/GetDatasheetFilePathAbsoluteEventInterface.php

Description: add a new event interface GetDatasheetFilePathAbsoluteEventInterface
related core pr: https://github.com/demos-europe/demosplan-core/pull/1615

F add GetDatasheetFilePathAbsoluteEventInterface

---

CHANGELOG.md
src/Contracts/Entities/UserInterface.php

Description: 
adjust UserInterface: these adjustements are made with https://github.com/demos-europe/demosplan-core/pull/1652

F adjust user interface

---

CHANGELOG.md
src/Contracts/Services/ProcedureNewsServiceInterface.php

Ticket:
https://yaits.demos-deutschland.de/T32776
Description:
add interface needed for xBeteiligungAsyncAddon

feature (refs T32776) add interface needed for xBeteiligungAsyncAddon

---

src/Permission/PermissionEvaluatorInterface.php

Must be merged together with https://github.com/demos-europe/demosplan-core/pull/1737.

feature: add `PermissionEvaluatorInterface::requireAllPermissions`

---

composer.json
src/Contracts/ApiRequest/ApiPaginationInterface.php
src/Contracts/ResourceType/AddonResourceType.php
src/Contracts/ResourceType/JsonApiResourceTypeInterface.php
src/Contracts/ResourceType/JsonApiResourceTypeServiceInterface.php
src/Logic/ApiRequest/DoctrineOrmPartialDTOProvider.php
src/Logic/ApiRequest/DqlFluentQuery.php
src/Logic/ApiRequest/FluentRepository.php
src/Logic/ApiRequest/PartialDTO.php

Must be merged with: https://github.com/demos-europe/demosplan-core/pull/1799

fix (refs T34139): allow resource type code reusabiliy

---

CHANGELOG.md
src/Contracts/Services/ParagraphServiceInterface.php

To make the ParagraphService in addons available we have to add a ParagraphServiceInterface.
Core PR: https://github.com/demos-europe/demosplan-core/pull/2252

feat (T35051): Add ParagraphServiceInterface

---

CHANGELOG.md

raise version, adjust changelog

chore: prepare release 0.11

---

CHANGELOG.md

minor: adjust date of change-log-entry

---

CHANGELOG.md
composer.json
src/Contracts/Entities/ProcedureInterface.php

Ticket:
https://yaits.demos-deutschland.de/T34551
Description:
adjust ProcedureInterface due to method-declaration changes
Linked PRs:
https://github.com/demos-europe/demosplan-core/pull/2514

feature (refs T33578) adjust ProcedureInterface due to method-declaration changes

---

composer.json

Description: adjust demosplan-addon version in composer json ( there is a new version v0.23 )

f adjust demosplan-addon version in composer json

---

CHANGELOG.md

f adjust CHANGELOG

---

CHANGELOG.md
composer.json

Description: technical release to heal release problem in previous version
- adjust CHANGELOG and demosplan-addon version in composer json

F technical release to heal release problem in previous version

---

CHANGELOG.md
src/Contracts/Entities/UserInterface.php

Ticket: 
https://yaits.demos-deutschland.de/T30474
Description:
fix user interface method declaration due to changes within core

feature (refs T30474) fix the UserInterface second attempt

---

CHANGELOG.md
composer.json

Ticket: 
https://yaits.demos-deutschland.de/T30474
Description:
update version due to changes made in https://github.com/demos-europe/demosplan-addon/pull/95

feature (refs T30474) update version

---

CHANGELOG.md
composer.json
src/Contracts/Entities/ProcedurePhaseInterface.php

New property on procedure phase needs to be available

feat (refs T36340): allow iteration of a procedure phase

---

CHANGELOG.md
composer.json
src/Contracts/Entities/ProcedureInterface.php
src/Contracts/Entities/ProcedurePhaseInterface.php

Do not merge before https://github.com/demos-europe/demosplan-core/pull/2889 is merged

T36340: Own entity for Phase(s) of a procedure

---

CHANGELOG.md
composer.json

prepare release 0.29
Do not merge before https://github.com/demos-europe/demosplan-core/pull/2826 is merged

chore: prepare release 0.29

---

CHANGELOG.md
src/Contracts/Repositories/ProcedurePhaseRepositoryInterface.php

**Ticket: ** https://demoseurope.youtrack.cloud/issue/DPLAN-11355/DiPlanBeteiligung-generiert-korrekte-XBeteiligung-Nachrichteninhalte-fur-die-Raumordnung
Adds the ProcedurePhaseRepositoryInterface for usage in addons.

feat (DPLAN-11355): add ProcedurePhaseRepositoryInterface

---

CHANGELOG.md
composer.json

**Ticket: ** https://demoseurope.youtrack.cloud/issue/DPLAN-11355/DiPlanBeteiligung-generiert-korrekte-XBeteiligung-Nachrichteninhalte-fur-die-Raumordnung
prepare release 0.30

chore: prepare release 0.30

---

CHANGELOG.md
composer.json
src/Contracts/FileServiceInterface.php

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_boards/board/t/BOP-HH-Team/Arbeitselemente
Description:
implement needed method within the FileserviceInterface

feature (refs ADO_2024.6.0) implement needed method in FileServiceInterface

---

CHANGELOG.md
composer.json

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11487/Update-EDT-auf-0.24.42
Description: add edt dependencies

f DPLAN-11487 adjust edt dependencies versions

---

CHANGELOG.md
composer.json
src/Contracts/Events/StatementCreatedViaExcelEventInterface.php

Ticket: https://demoseurope.youtrack.cloud/issue/DPLAN-11494/Nach-Excel-Import-von-verschlagworteten-Abschnitten-werden-trotzdem-keine-Vorschlage-bei-Slicing-Tagging-angezeigt
Description: add event interface.

F dplan 11494  add interface

---

CHANGELOG.md
composer.json
src/Contracts/Handler/SingleDocumentHandlerInterface.php
src/Contracts/Services/ProcedureServiceStorageInterface.php

Ticket:
https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/15514
Description:
implement missing methods in SingleDocumentInterface needed for tests to mock those.

feature (refs ADO_2024.6.0) implement missing methods in SingleDocumentInterface

---

CHANGELOG.md

final PR to solve the version conflicts

F fix version hick ups

---

CHANGELOG.md
composer.json
src/Contracts/Factory/BoilerplateCategoryFactoryInterface.php
src/Contracts/Factory/BoilerplateFactoryInterface.php

Ticket: https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/16632
Description: use factory to can create object

feature (refs ADO-16632): create factoryInterface

---

CHANGELOG.md
composer.json
src/Contracts/Entities/DepartmentInterface.php
src/Contracts/Entities/OrgaInterface.php
src/Contracts/MessageBagInterface.php

Tightenco\Collect has been deprecated, Illuminate\Support\Collection should be used instead 
https://github.com/tighten/collect

Update deprecated Tightenco\Collect to Illuminate\Support\Collection

---

CHANGELOG.md
composer.json
src/Contracts/Entities/ProcedureSettingsInterface.php

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
Due to new properties of the ProcedureSettings - its corresponding interface got updated here. https://github.com/demos-europe/demosplan-core/pull/3889

feature (refs BEAA2-10) bump ProcedureSettingsInterface

---

CHANGELOG.md
composer.json
src/Contracts/ResourceType/OrgaResourceTypeInterface.php

Ticket:
https://demoseurope.youtrack.cloud/issue/BEAA2-10/AP-1-Schnittstellenumsetzung-zwischen-DiPlanBeteiligung-und-mein.berlin.de
Description:
add OrgaResourceTypeInterface

feature (refs BEAA2-10) add OrgaResourceTypeInterface

---

CHANGELOG.md
composer.json
src/Contracts/Services/MapProjectionConverterInterface.php
src/Contracts/ValueObject/CoordinatesViewportInterface.php

add CoordinatesViewportInterface and MapProjectionConverterInterface for map related tasks

chore: add Interfaces for map related tasks

---

CHANGELOG.md
composer.json
src/Contracts/Entities/StatementInterface.php

Ticket:
https://demoseurope.youtrack.cloud/issue/DPLAN-14943/Kommentar-in-Erwiderung-ladt-unendlich
Description:
Add new Statement validation group used for base statements only (non segments)

feature (refs DPLAN-14943) add new EventInterface for AddonInterCom

---

CHANGELOG.md
composer.json

Update version to v0.52

---

CHANGELOG.md
composer.json
src/Contracts/PlaceServiceInterface.php

relase version 0.53 to fix return type on getting workflowplace

---

CHANGELOG.md
composer.json

bump Version

---

CHANGELOG.md
src/Contracts/Services/CustomerServiceInterface.php

Add CustomerServiceInterface contract for customer operations including:
- findCustomerById, findCustomersByIds
- findCustomerBySubdomain
- getCurrentCustomer, updateCustomer, createCustomer
- getReservedCustomerNamesAndSubdomains

chore: add CustomerServiceInterface
